package assignmnet8;

public class Bank {

	
	private int pin;
	
	
	public void setpin(int pin) {
		
		this.pin=pin;		
		
	}
	
	public int getpin() {
		
		
		return pin;
	}
	
	public void validatepin() {
		
		
		
		
		if(pin==1001 || pin==1234 || pin==1212) {System.out.println("PIN generated by user is a Valid PIN");}
			
		else {System.out.println("PIN generated by user is an Invalid PIN");	}	
			
		}
		
		}

