package assignmnet8;

public class User {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
Bank bn=new Bank();
bn.setpin(4567);

System.out.println("PIN generated by user is :"+" "+bn.getpin());

bn.validatepin();
	}

}
